name: Gunluk Python Calistirici

on:
  schedule:
    # Bu kısım cron dilidir. Örnek: Her gün gece 03:00'te çalışır.
    - cron: '0 3 * * *' 
  workflow_dispatch: # Bu satır, senin manuel olarak "Simdi Calistir" demene izin verir.

jobs:
  build:
    runs-on: ubuntu-latest # Sana bedava bir Linux (Ubuntu) acar.

    steps:
    - name: Depoyu Kopyala
      uses: actions/checkout@v3 # Kodlarını Linux makinesine ceker.

    - name: Python Kur
      uses: actions/setup-python@v4
      with:
        python-version: '3.9' # Python surumunu ayarlar.

    - name: Kutuphaneleri Yukle
      run: |
        pip install -r requirements.txt

    - name: Kodu Calistir
      run: python main.py
